### ISSUE TITLE
Running in Inductive mode

### ISSUE THREAD

**Issue by khangtran2020** [sisaman/GAP#9]
Hi authors,

Is there a way to run GAP in the inductive setting?

Thank you.

**Comment by sisaman** [comment]
The current GAP implementation supports both transductive and inductive settings, but the existing datasets (Facebook, Reddit, Amazon) are all transductive.

You can extend the [DatasetLoader](https://github.com/sisaman/GAP/blob/master/core/datasets/loader.py) class to add support for inductive datasets. Note that the train, validation, and test subgraphs of the inductive dataset must be integrated into a single `Data` object so that it works seamlessly with the rest of the code.

**Comment by khangtran2020** [comment]
Thank you, I have modified the code to run in Inductive mode. Thank you very much.
